# Generated by Django 5.0.6 on 2024-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro_movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('alarme_id', models.IntegerField()),
                ('raspberry_id', models.IntegerField()),
                ('dispositivo_id', models.CharField(max_length=36)),
            ],
        ),
    ]
